---
# tasks file for hello-world

- name: Test jinja2template
  template: src=helloworld.txt.j2 dest=helloworld.txt
  tags:
    - hello_world

- name: Test per-entry indexing
  include: per-entry-actions.yml
  with_indexed_items: "{{ test_demand_partners }}"
  loop_control:
    loop_var: inventory
  tags:
    - per_entry

- name: Test child fold tasks
  include: subtasks/main.yml
  with_items:
    - "bob villa"
    - "bob ross"
  loop_control:
    loop_var: bob
  tags:
    - sub_task

- name: Test looping over a dictionary
  include: loop-over-dict.yml
  with_items:
    - first_name: "Bob"
      last_name: "Villa"
    - first_name: "Bob"
      last_name: "Ross"
  loop_control:
    loop_var: bob
  tags:
    - dict_loop
